### ISSUE TITLE
Hawtio not connected

### ISSUE THREAD

**Issue by simasch** [wildfly-extras/wildfly-camel#1025] opened 2016-01-18 09:18 UTC
When I start WildFly I don't see anything in Hawtio:

![clipboard01](https://cloud.githubusercontent.com/assets/593352/12387438/ce6728e4-bdcc-11e5-8992-b9e191de2d03.png)

**Comment by jamesnetherton** [comment] 2016-01-18 09:29
Is this with a specific release version? Or when building directly from the master branch?

**Comment by simasch** [comment] 2016-01-18 09:57
This is the Release 3.2.0
https://github.com/wildfly-extras/wildfly-camel/releases/tag/3.2.0

Sorry for not mentioning

**Comment by jamesnetherton** [comment] 2016-01-18 11:46
It's working Ok for me. I notice you're using Windows, in theory that shouldn't be an issue, but I can verify later today. 

Are there any errors output to the chrome console? You can view it with `ctrl + shift + j`.

**Comment by simasch** [comment] 2016-01-18 12:38
When I start hawtio and I'm not logged in I see this console

![hawtio_start](https://cloud.githubusercontent.com/assets/593352/12391525/b4011dcc-bde8-11e5-94f4-aa9cbada6374.png)

**Comment by simasch** [comment] 2016-01-18 13:05
We found the problem. It was the ActiveMQ rar in the deployment folder.
How do you define a resource adapter for ActiveMQ as module or deployment?

**Comment by simasch** [comment] 2016-01-18 13:26
Ok finally got it up and running. I had to install the resource adapter as module. 

Deployment of the *.rar seems not to be supported...

**Comment by jamesnetherton** [comment] 2016-01-18 14:16
Deployment of a RAR is supported. See documentation here:

https://wildflyext.gitbooks.io/wildfly-camel/content/components/camel-activemq.html

You just need to ensure that you reference the correct archive name within the RA subsystem configuration. E.g if you deployed the archive as `activemq-rar.rar` then the config would be:
```
<archive>activemq-rar.rar</archive>
```

**Comment by jamesnetherton** [comment] 2016-01-18 14:17
Looks like this isn't a Hawtio problem, so closing issue.

**Comment by simasch** [comment] 2016-01-18 14:21
When I do this as described in here
https://wildflyext.gitbooks.io/wildfly-camel/content/components/camel-activemq.html

Hawtio does not work anymore! That's the reason for this case

**Comment by jamesnetherton** [comment] 2016-01-18 14:29
Sorry, my bad. I'll reopen this one and close the duplicate.

**Comment by jamesnetherton** [comment] 2016-01-20 12:30
So far, I've not been able to reproduce this.

I'm testing on Windows with the ActiveMQ RA config present in standalone-camel.xml. Whenever I log into Hawtio, I always get the 'Connect, Dashboard, JBoss, JMX, Threads' toolbar.

Are you using the Hawtio version that is supplied with the wildfly-camel subsystem patch? Or did you download and deploy it yourself?

**Comment by simasch** [comment] 2016-01-20 13:17
Yes I have the hawtio that comes with the camel subsystem.
Do you have activmq-*.rar in deployments folder? We use activemq-rar-5.12.1.rar

**Comment by jamesnetherton** [comment] 2016-01-20 13:40
Yes, the RA is in the deployments folder and it's the 5.12.1 version.

**Comment by simasch** [comment] 2016-01-20 14:55
When I start without activemq-rar-5.12.1.rar deployed it works fine (before_deployment)
When I start with activemq-rar-5.12.1.rar deployed it works fine (after_deployment)

![before_deployment](https://cloud.githubusercontent.com/assets/593352/12452329/30f39354-bf8e-11e5-952d-10ce22c94091.png)
![after_deployment](https://cloud.githubusercontent.com/assets/593352/12452330/30f3e32c-bf8e-11e5-8fb5-74b185eba440.png)

**Comment by jamesnetherton** [comment] 2016-01-20 15:22
Still can't reproduce it. Are you able to share your resource adapter configuration? Or is it identical to the example from the documentation?

**Comment by simasch** [comment] 2016-01-20 16:41
I don't have any resource adapter configured. 
I just deployed the RAR and then hawtio is broken

**Comment by jamesnetherton** [comment] 2016-03-31 07:51
Likely that this is related to: https://issues.jboss.org/browse/ENTESB-5062

**Comment by jamesnetherton** [comment] 2016-05-20 12:41
Just updated the project to HawtIO 1.4.65 which should contain a fix for this problem.

I'll reopen if not.

**Closed by jamesnetherton** 2016-05-20 12:41 UTC
Labels: bug, console
