### ISSUE TITLE
Hawt.io Route Diagram not available

### ISSUE THREAD

**Issue by myfear** [wildfly-extras/wildfly-camel#765] opened 2015-07-17 09:37 UTC
Clicking on "camel" > a route > "Route Diagram" gives this exception in the hawtio console:

Operation unknown failed due to: javax.management.RuntimeErrorException : Error occurred in RequiredModelMBean while trying to invoke operation dumpRoutesAsXml

Can confirm, that it was working with 2.2.0

**Comment by jamesnetherton** [comment] 2015-07-17 09:50
Now that we've moved to WildFly 9 and have a newer version of JAXB, we potentially want to revert the work that we did for #608 (although EAP still needs this change).

**Comment by tdiesler** [comment] 2015-07-17 11:29
Is this still happening in master?

**Comment by myfear** [comment] 2015-07-17 11:41
I only work with releases. Should look into building master and giving I a
shot there.

**Comment by grgrzybek** [comment] 2015-07-21 13:18
I'll check this.

**Comment by grgrzybek** [comment] 2015-07-23 14:18
@myfear I just checked with latest build from jboss-fuse/wildfly-camel, will try with wildfly-extras/wildfly-camel 3.0 branch now

**Comment by myfear** [comment] 2015-07-23 14:55
I did a few more runs,  too.
Couldn't reproduce it reliably. It sometimes occurs after redeploys. Works
95 percent of the time.
Do you have any idea,  if there's something particular to look at?
It's always the dumoRouteToXML method that generates the problem.

M

**Comment by grgrzybek** [comment] 2015-07-23 15:07
The ultimate reason was described [here](https://github.com/wildfly-extras/wildfly-camel/issues/608#issuecomment-100236715) and the problem was wrong TCCL available at the time of invoking this method...

Checking with `master` branch now.

**Comment by grgrzybek** [comment] 2015-07-23 15:33
Everything's fine on `master` branch. I see my TCCL setting wrapper is not used anymore, but it should be no problem with WF9 which uses newer JAXB libraries.

**Comment by grgrzybek** [comment] 2015-07-23 15:34
@myfear can you provide an example and exact branch you're testing? I'll check ... after holidays ...

**Comment by myfear** [comment] 2015-07-23 15:54
Releases only: 2.2.0 and 2.3.0 on wildfly 8.2.0.final.

Thanks!
M

**Comment by lucasweb78** [comment] 2015-07-28 21:49
Am seeing the same issue here with 2.3.0 on Wildfly 8.2.1. Would be great to see this fixed for Wildfly 8.2.x as moving to Wildfly 9 is not an option for me in the short term.

**Comment by grgrzybek** [comment] 2015-08-02 06:46
I'm on holidays without access to any environment. I'll check on August 10th.

**Comment by grgrzybek** [comment] 2015-08-17 10:47
@myfear @lucasweb78 I've checked again

* `unzip wildfly-8.2.1.Final.zip`
* fresh build of `wildfly-camel-patch-2.3.0.tar.gz` directly [from tag 2.3.0](https://github.com/wildfly-extras/wildfly-camel/tree/2.3.0)
* `tar xf wildfly-camel-patch-2.3.0.tar.gz` into `$WILDFLY_HOME`
* `bin/addUser.sh` (I've added `admin` management user)
* `bin/standalone.sh -c standalone-camel.xml`
* browse to http://localhost:8080/hawtio - no "Camel" tab, because no Camel context is deployed
* `cp jboss-fuse/wildfly-camel/itests/standalone/src/main/resources/spring/transform1-camel-context.xml $WILDFLY_HOME/standalone/deployments`

After the above steps I could see source of the route and Camel diagram. After restarting WF, I still had no problems.

Could you please provide some *steps to reproduce*?

**Comment by jamesnetherton** [comment] 2015-08-19 10:26
@grgrzybek I think I can reliably replicate the problem by deploying this sample application:

https://github.com/myfear/camel-javaee-bankdemo

Tried multiple redeploys, starting / stopping the server but I always hit errors when trying to view Camel routes.

**Comment by grgrzybek** [comment] 2015-08-19 10:29
@jamesnetherton thanks - I tried only `transform1-camel-context.xml`...

**Comment by jamesnetherton** [comment] 2015-08-19 10:33
It works fine with WildFly 9 and WFC 3.0.0. Not sure what the merits are of digging any further into this problem, as I don't think there were any plans to cut more releases for WildFly 8 (I.e we'd need to branch and release from the 2.3.0 tag to be able to fix this).

**Comment by jamesnetherton** [comment] 2015-08-19 10:45
This problem is also present on EAP 6.4, so it looks like we do need to resolve this.

**Comment by grgrzybek** [comment] 2015-08-27 07:00
The reason is the same - `null` TCCL. But this time not when creating `JAXBContext`, but during `marshall()` invocation. I have one idea - checking.

**Comment by grgrzybek** [comment] 2015-08-27 08:53
for EAP: https://github.com/jboss-fuse/wildfly-camel/pull/64

**Comment by tdiesler** [comment] 2015-09-08 08:54
Please create an EAP issue for this in jira. Its not a wfc community issue any more

**Closed by tdiesler** 2015-09-08 08:54 UTC
Labels: out of date
