### ISSUE TITLE
Use docker-maven-plugin to generate images

### ISSUE THREAD

**Issue by tdiesler** [wildfly-extras/wildfly-camel#98] opened 2014-11-24 15:59 UTC
Currently blocked by https://github.com/rhuss/docker-maven-plugin/issues/53

**Comment by jamesnetherton** [comment] 2015-06-04 12:36
This is semi-fixed in the current plugin version. But, there is still no means of configuring an entrypoint for the build goal (it's exclusive to the run goal). 

Looks like 0.12.0 will fix this: https://github.com/rhuss/docker-maven-plugin/pull/156.

**Comment by jamesnetherton** [comment] 2015-06-15 16:19
Confirmed that the 0.12.0 plugin version fixes the outstanding issues. Now blocked by #541.

**Closed** 2015-07-20 10:34 UTC
Labels: docker, task
